name: Installation Test

on:
  push:
    branches: [main, stable]
  pull_request:
    branches: [main, stable]

env:
  PYTHON_VERSION: "3.12"

jobs:
  run_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install pamiq-io
        run: |
          python -m pip install .
          python -c "import pamiq_io;print(pamiq_io.__version__)"
